### ISSUE TITLE
임베디드 몽고, 레디스 Spring 3.0 호환여부 조사

### ISSUE THREAD

**Issue by brewagebear** [The-Gleaners/streaming-system#18]
## 배경

스프링 부트 3.0 버전에서 임베디드 몽고디비와 레디스의 호환여부 조사

## 진행사항
 - [x] 스프링 부트 3.0 + 임베디드 몽고디비 동작확인
 - [x] 스프링 부트 3.0 + 임베디드 레디스 동작확인

## 공유사항

연관된 라이브러리 코드베이스 주소 
- https://github.com/ozimov/embedded-redis (3년 전이 마지막 PR) 
- https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo (최근 릴리즈 3월)

**Comment by brewagebear** [comment]
@suhongkim98 님께서 레디스는 확인해주시기로 하셨습니다.

**Comment by suhongkim98** [comment]
`embeeded redis` 동작 확인하였고 위키에 문서화 해두었습니다.

**Comment by brewagebear** [comment]
@suhongkim98 님 작업한 모듈 PR 올려주시면 그거 토대로 임베디드 몽고 모듈도 업데이트하도록 하겠습니다.

**Comment by brewagebear** [comment]
@suhongkim98 님 스프린트 단위로 프로젝트를 나누기로 해서 모듈 작업은 2주차 스프린트에 이슈 새로 할당해서 작업해주시면 될 것 같습니다.

**Comment by suhongkim98** [comment]
넵 알겠습니다.
