### ISSUE TITLE
겁나빠른 다운로더 개발

### ISSUE THREAD

**Issue by brewagebear** [The-Gleaners/streaming-system#2]

**Comment by lim-12** [comment]
@brewagebear 
이슈 관련하여 궁금한 부분이 있습니다.
빠른 다운로더는 다운로더 자체를 빨리하려는 이슈인가요 ? 아니면 다운로드하며 처리되는 데이터들을 최대한 빨리 처리하려는 이슈인가요 ?

예를 들어, "www.xxxx.com/file.tsv" 에 접근하여 파일을 다운로드할 때 걸리는 시간이 1시간이라고 가정합니다. ( 업체 최대 다운로드 속도 및 파일 크기의 영향 )
파일 다운로드를 50분, 40분으로 줄이는 것이 목표인가요 ? 아니면 다운로드한 row를 이용하여 추가 작업하는데까지 걸리는 시간을 1시간으로 만드는 것인가요 ?

**Comment by brewagebear** [comment]
@lim-12 님 

이 부분은 테스트로 남긴 이슈여서 좀 더 세분화해서 이슈 리스트 진행하도록 하겠습니다.
