### ISSUE TITLE
다운로드 라이브러리 리스팅 및 조사

### ISSUE THREAD

**Issue by lim-12** [The-Gleaners/streaming-system#3]
### 이슈 내용
Java 에서 http 로 접근하여 파일을 다운로드하는 라이브러리들을 리스팅한다.
리스팅한 라이브러리들의 사용 방법 및 성능 테스트를 진행한다.

**Comment by brewagebear** [comment]
저는 아래와 같이 리서치를 할 예정입니다.

조건
1. mkfile을 토대로 임의의 1기가 파일 생성
2. 고전 방식의 ThreadPool 다운로드 구현 
3. NIO를 통한 다운로드 구현 

Netty를 통한 다운로드 구현

각각 성능 테스트 수행하고자 하는데 방향성 검토 요청드릴 수 있을까요?

**Comment by lim-12** [comment]
@brewagebear 
좋은 거 같습니다.
저는 일단 io, nio, http 쪽에 있는 라이브러리 활용하여 다운로드 테스트 진행해보도록 하겠습니다. ( 병렬 조건 없이 순수 성능 체크 용도 )

**Comment by brewagebear** [comment]
[리서치 내용](https://github.com/The-Gleaners/streaming-system/wiki/%5BStudy%5D-Java-Http-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%A1%B0%EC%82%AC-%EB%B0%8F-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-%EB%B0%A9%EC%8B%9D%EC%97%90-%EB%94%B0%EB%A5%B8-%EC%84%B1%EB%8A%A5%ED%85%8C%EC%8A%A4%ED%8A%B8)

리서치 내용 위키에 추가하였고, 이에 이슈 닫힘처리 진행하였습니다.
