### ISSUE TITLE
카프카 설정 및 컨슈머, 프로듀서 개발

### ISSUE THREAD

**Issue by lim-12** [The-Gleaners/streaming-system#7]
### 이슈 내용
- 트리거를 통해 넘어오는 메세지를 받기 위한 컨슈머를 개발한다. ( API 콜로 변경될 수도 있기 때문에 확정은 아니다. )
- 다운로드 완료 후, 생성 된 product를 프로세서로 넘겨줄 프로듀서를 개발한다.

**Comment by brewagebear** [comment]
작업 완료하여 해당 이슈 닫힘처리 진행하도록 하겠습니다.
